# 开发环境配置

# 数据源配置
spring:
    datasource:
        url: jdbc:mysql://10.9.242.26:3306/dmp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: zjgg@YFZX1q2w3e4r
        driver-class-name: com.mysql.cj.jdbc.Driver
    # Redis 连接参数 （RedisProperties）
    redis:
        host: 10.9.243.92
        port: 6379
        ssl: false
        database: 0
        password: znzz@ZJGG100
        timeout: 20000
        lettuce:
            pool:
                #最大连接数
                max-active: 1000
                #最大阻塞等待时间(负数表示没限制)
                max-wait: -1
                #最大空闲
                max-idle: 10
                #最小空闲
                min-idle: 5
#    redis:
#        password: znzz@ZJGG100
#        cluster:
#            nodes: 10.9.247.183:9001,10.9.247.183:9002,10.9.247.184:9003,10.9.247.184:9004,10.9.247.185:9005,10.9.247.185:9006
#            max-redirects: 3
#        lettuce:
#            pool:
#                max-idle: 100
#                max-active: 200
#                min-idle: 20

# 日志配置
logging:
    level:
        com.cscec: warn
        com.baomidou.mybatisplus: warn

mqtt:
    enabled: true
    host: "tcp://10.9.243.92:1883"
    clientKey: "CSCEC-DMP-"
    username: "admin"
    password: "zjgg@yfzx"
#    topic: "CSCEC-DMP/#"
    topic: CSCEC-DMP/#, JANTOUR/UP/#
    completionTimeout: 10000
    connectionTimeout: 10000