# 开发环境配置

# 数据源配置
spring:
    datasource:
        url: jdbc:mysql://10.50.103.184:3306/dmp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

    redis:
        host: 10.50.103.184
        port: 6379
        password: zjgg@123
        timeout: 20000
        lettuce:
            pool:
                #连接池最大连接数
                max-active: 1000
                # 连接池最大等待时间，-1表示不做限制
                max-wait: 100ms
                # 最大空闲连接
                max-idle: 5
                # 最小空闲连接
                min-idle: 1

# 日志配置
#logging:
#    level:
#        com.kgz: DEBUG
#        com.baomidou.mybatisplus: DEBUG

mqtt:
    enabled: true
    host: "tcp://58.251.8.11:1883"
    clientKey: "CSCEC-DMP-"
    username: "admin"
    password: "zjgg@yfzx"
#    ","分割,传多个参数
    topic: CSCEC-DMP/#, JANTOUR/UP/#
#    topic: CSCEC-DMP/#
    completionTimeout: 10000
    connectionTimeout: 10000